import type {
  CertificateData,
  RegisterRow,
  ScheduleData,
} from "./types.js";

const ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

/** Escape a value for safe HTML interpolation. */
export function esc(value: unknown): string {
  return String(value).replace(/[&<>"']/g, (c) => ESCAPES[c] ?? c);
}

export const inr = (n: number): string =>
  "₹" + n.toLocaleString("en-IN", { minimumFractionDigits: 2 });

/** Shared document chrome: print-friendly, single-theme (it is a paper form). */
function page(title: string, body: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
  :root{--ink:#12211d;--muted:#5a675f;--line:#c9d0ca;--accent:#a9741c;--paper:#fbfbf8}
  *{box-sizing:border-box}
  body{margin:0;background:#e9ece7;color:var(--ink);
    font-family:"Segoe UI",system-ui,-apple-system,Roboto,Helvetica,Arial,sans-serif;line-height:1.5}
  .sheet{max-width:760px;margin:1.5rem auto;background:var(--paper);border:1px solid var(--line);
    padding:2rem 2.25rem;position:relative;overflow:hidden}
  .specimen{position:absolute;top:38%;left:-6%;width:120%;text-align:center;
    font-size:6rem;font-weight:800;color:rgba(169,116,28,.08);transform:rotate(-18deg);
    letter-spacing:.1em;pointer-events:none;user-select:none}
  header{display:flex;justify-content:space-between;align-items:flex-start;
    border-bottom:2px solid var(--accent);padding-bottom:.75rem;margin-bottom:1.25rem}
  .brand{font-weight:700;font-size:1.05rem}
  .brand small{display:block;font-weight:400;color:var(--muted);font-size:.72rem;letter-spacing:.08em}
  .doctype{text-align:right;font-size:.72rem;color:var(--muted);text-transform:uppercase;letter-spacing:.12em}
  h1{font-size:1.15rem;margin:0 0 1rem}
  table{width:100%;border-collapse:collapse;margin:.5rem 0 1rem}
  th,td{text-align:left;padding:.4rem .5rem;border-bottom:1px solid var(--line);vertical-align:top;font-size:.9rem}
  th{color:var(--muted);font-weight:600;width:38%}
  .money{text-align:right;font-variant-numeric:tabular-nums}
  .total td{border-top:2px solid var(--accent);border-bottom:none;font-weight:700}
  .foot{margin-top:1.5rem;font-size:.72rem;color:var(--muted);border-top:1px solid var(--line);padding-top:.6rem}
  @media print{body{background:#fff}.sheet{border:none;margin:0}}
</style></head><body><div class="sheet"><div class="specimen">SPECIMEN</div>
<header><div class="brand">OpenCover reference insurer<small>OPEN-SOURCE P&amp;C CORE · NOT A REAL INSURER</small></div>
<div class="doctype">${esc(title)}</div></header>
${body}
<div class="foot">Specimen generated by OpenCover for demonstration. Not a contract of insurance.</div>
</div></body></html>`;
}

/** The policy schedule / declarations page. */
export function renderPolicySchedule(d: ScheduleData): string {
  const coverages = d.coverages
    .map((c) => `<tr><th>${esc(c.name)}</th><td>${esc(c.detail)}</td></tr>`)
    .join("");
  const premium = d.premium.lines
    .map(
      (l) =>
        `<tr><td>${esc(l.label)}</td><td class="money">${inr(l.amount)}</td></tr>`,
    )
    .join("");

  return page(
    "Policy Schedule",
    `<h1>Private Car Policy — Schedule</h1>
<table>
  <tr><th>Policy number</th><td>${esc(d.policyNumber)}</td></tr>
  <tr><th>Insured</th><td>${esc(d.insuredName)}</td></tr>
  <tr><th>Product</th><td>${esc(d.product)} (v${esc(d.productVersion)})</td></tr>
  <tr><th>Period of insurance</th><td>${esc(d.period.from)} to ${esc(d.period.to)}</td></tr>
  <tr><th>Registration no.</th><td>${esc(d.vehicle.registrationNo)}</td></tr>
  <tr><th>Vehicle</th><td>${esc(d.vehicle.description)} · ${esc(d.vehicle.cc)} cc · RTO zone ${esc(d.vehicle.rtoZone)}</td></tr>
  <tr><th>Insured declared value (IDV)</th><td>${inr(d.vehicle.idv)}</td></tr>
  <tr><th>No-claim bonus</th><td>${esc(d.ncb)}%</td></tr>
</table>
<h1>Coverages</h1>
<table>${coverages}</table>
<h1>Premium</h1>
<table>${premium}<tr class="total"><td>Total premium payable</td><td class="money">${inr(d.premium.total)}</td></tr></table>`,
  );
}

/** Certificate of Insurance — Form 51 (Central Motor Vehicles Rules). */
export function renderForm51(d: CertificateData): string {
  return page(
    "Certificate of Insurance — Form 51",
    `<h1>Certificate of Insurance (Form 51)</h1>
<table>
  <tr><th>Certificate no.</th><td>${esc(d.certificateNumber)}</td></tr>
  <tr><th>Policy no.</th><td>${esc(d.policyNumber)}</td></tr>
  <tr><th>Registration mark of vehicle</th><td>${esc(d.vehicle.registrationNo)}</td></tr>
  <tr><th>Description of vehicle</th><td>${esc(d.vehicle.description)}</td></tr>
  <tr><th>Name of insured</th><td>${esc(d.insuredName)}</td></tr>
  <tr><th>Effective date of commencement of insurance</th><td>${esc(d.period.from)}, 00:00</td></tr>
  <tr><th>Date of expiry of insurance</th><td>${esc(d.period.to)}, 23:59</td></tr>
  <tr><th>Persons or classes of persons entitled to drive</th>
      <td>The insured, or any person driving on the insured's order or with permission, holding a valid licence.</td></tr>
  <tr><th>Limitations as to use</th><td>Use for social, domestic and pleasure purposes and for the insured's business. Excludes hire or reward, organised racing, and speed testing.</td></tr>
  <tr><th>Limits of liability — third-party property damage</th><td>${esc(d.tp.propertyDamage)}</td></tr>
  <tr><th>Limits of liability — third-party bodily injury</th><td>${esc(d.tp.bodilyInjury)}</td></tr>
  <tr><th>Issued at</th><td>${esc(d.issuedAt)}</td></tr>
</table>
<p style="font-size:.82rem;color:var(--muted)">I hereby certify that the policy to which this certificate relates
satisfies the requirements of the relevant law applicable in India.</p>`,
  );
}

const CSV_COLUMNS: Array<keyof RegisterRow> = [
  "policyNumber",
  "product",
  "inception",
  "expiry",
  "sumInsured",
  "odPremium",
  "tpPremium",
  "gst",
  "total",
];

/** IRDAI-style premium register: one row per issued policy, CSV. */
export function renderPremiumRegisterCsv(rows: RegisterRow[]): string {
  const header = CSV_COLUMNS.join(",");
  const body = rows.map((r) => CSV_COLUMNS.map((c) => r[c]).join(",")).join("\n");
  return rows.length ? `${header}\n${body}` : header;
}
